[project]
name = "Open Chemistry tools"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.3.2",
    "pyscf>=2.10.0",
    "simpletooling @ git+https://github.com/EvoEvolver/simpletooling.git",
]
